import { randomUUID } from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { requireAuth, type AuthedRequest } from "../auth";
import { db, now } from "../db";

export const resourceRoutes = Router();
resourceRoutes.use(requireAuth);
const mapRows = (rows: any[]) => rows.map((row) => ({ ...row, active: row.active === undefined ? undefined : Boolean(row.active), payload: row.payload ? JSON.parse(row.payload) : undefined }));

resourceRoutes.get("/watchlist", (request: AuthedRequest, response) => response.json({ items: mapRows(db.prepare("SELECT id,symbol,name,group_name AS groupName,created_at AS createdAt FROM watchlist WHERE user_id=? ORDER BY created_at DESC").all(request.userId) as any[]) }));
resourceRoutes.post("/watchlist", (request: AuthedRequest, response) => { const parsed = z.object({ symbol: z.string().regex(/^\d{6}(?:\.(?:SZ|SH))?$/), name: z.string().min(1).max(30), groupName: z.string().min(1).max(30).default("默认分组") }).safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "invalid_watchlist_item" }); const id = randomUUID(); try { db.prepare("INSERT INTO watchlist (id,user_id,symbol,name,group_name,created_at) VALUES (?,?,?,?,?,?)").run(id, request.userId, parsed.data.symbol, parsed.data.name, parsed.data.groupName, now()); response.status(201).json({ id, ...parsed.data }); } catch { response.status(409).json({ error: "already_in_watchlist" }); } });
resourceRoutes.delete("/watchlist/:id", (request: AuthedRequest, response) => { const result = db.prepare("DELETE FROM watchlist WHERE id=? AND user_id=?").run(request.params.id, request.userId); response.status(result.changes ? 204 : 404).end(); });

const alertSchema = z.object({ symbol: z.string().regex(/^\d{6}(?:\.(?:SZ|SH))?$/), name: z.string().min(1).max(30), kind: z.enum(["price", "change_percent", "volume"]), operator: z.enum(["gte", "lte"]), targetValue: z.number().finite(), intervalName: z.string().max(20).default("实时") });
resourceRoutes.get("/alerts", (request: AuthedRequest, response) => response.json({ items: mapRows(db.prepare("SELECT id,symbol,name,kind,operator,target_value AS targetValue,interval_name AS intervalName,active,last_triggered_at AS lastTriggeredAt,created_at AS createdAt FROM alerts WHERE user_id=? ORDER BY created_at DESC").all(request.userId) as any[]) }));
resourceRoutes.get("/alerts/:id/events", (request: AuthedRequest, response) => { const owned = db.prepare("SELECT id FROM alerts WHERE id=? AND user_id=?").get(request.params.id, request.userId); if (!owned) return response.status(404).json({ error: "alert_not_found" }); response.json({ items: db.prepare("SELECT id,observed_value AS observedValue,message,created_at AS createdAt FROM alert_events WHERE alert_id=? ORDER BY created_at DESC LIMIT 100").all(request.params.id) }); });
resourceRoutes.post("/alerts", (request: AuthedRequest, response) => { const parsed = alertSchema.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "invalid_alert" }); const id = randomUUID(), timestamp = now(); db.prepare("INSERT INTO alerts (id,user_id,symbol,name,kind,operator,target_value,interval_name,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id, request.userId, parsed.data.symbol, parsed.data.name, parsed.data.kind, parsed.data.operator, parsed.data.targetValue, parsed.data.intervalName, timestamp, timestamp); response.status(201).json({ id, ...parsed.data, active: true }); });
resourceRoutes.patch("/alerts/:id", (request: AuthedRequest, response) => { const parsed = z.object({ active: z.boolean() }).safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "invalid_alert_patch" }); const result = db.prepare("UPDATE alerts SET active=?,updated_at=? WHERE id=? AND user_id=?").run(parsed.data.active ? 1 : 0, now(), request.params.id, request.userId); response.status(result.changes ? 204 : 404).end(); });
resourceRoutes.delete("/alerts/:id", (request: AuthedRequest, response) => { const result = db.prepare("DELETE FROM alerts WHERE id=? AND user_id=?").run(request.params.id, request.userId); response.status(result.changes ? 204 : 404).end(); });

resourceRoutes.get("/reports", (request: AuthedRequest, response) => response.json({ items: mapRows(db.prepare("SELECT id,symbol,name,interval,payload,data_status AS dataStatus,created_at AS createdAt,updated_at AS updatedAt FROM reports WHERE user_id=? ORDER BY created_at DESC LIMIT 100").all(request.userId) as any[]) }));
resourceRoutes.post("/reports", (request: AuthedRequest, response) => { const parsed = z.object({ symbol: z.string(), name: z.string(), interval: z.string(), imageId: z.string().uuid().optional(), payload: z.record(z.string(), z.unknown()), dataStatus: z.enum(["verified", "partial", "unavailable"]) }).safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "invalid_report" }); const id = randomUUID(), timestamp = now(); db.prepare("INSERT INTO reports (id,user_id,symbol,name,interval,image_id,payload,data_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id, request.userId, parsed.data.symbol, parsed.data.name, parsed.data.interval, parsed.data.imageId ?? null, JSON.stringify(parsed.data.payload), parsed.data.dataStatus, timestamp, timestamp); response.status(201).json({ id, createdAt: timestamp }); });
resourceRoutes.patch("/reports/:id", (request: AuthedRequest, response) => { const parsed = z.object({ symbol: z.string(), name: z.string(), interval: z.string(), payload: z.record(z.string(), z.unknown()), dataStatus: z.enum(["verified", "partial", "unavailable"]) }).safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "invalid_report" }); const result = db.prepare("UPDATE reports SET symbol=?,name=?,interval=?,payload=?,data_status=?,updated_at=? WHERE id=? AND user_id=?").run(parsed.data.symbol, parsed.data.name, parsed.data.interval, JSON.stringify(parsed.data.payload), parsed.data.dataStatus, now(), request.params.id, request.userId); response.status(result.changes ? 204 : 404).end(); });
resourceRoutes.get("/profile/stats", (request: AuthedRequest, response) => { const scalar = (table: string, extra = "") => (db.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE user_id=? ${extra}`).get(request.userId) as any).count; response.json({ reports: scalar("reports"), watchlist: scalar("watchlist"), activeAlerts: scalar("alerts", "AND active=1"), uploads: scalar("uploads") }); });
resourceRoutes.get("/reports/:id", (request: AuthedRequest, response) => { const row = db.prepare("SELECT id,symbol,name,interval,payload,data_status AS dataStatus,created_at AS createdAt FROM reports WHERE id=? AND user_id=?").get(request.params.id, request.userId) as any; if (!row) return response.status(404).json({ error: "report_not_found" }); response.json({ ...row, payload: JSON.parse(row.payload) }); });
