import { BellRing, Check, Clock3, LogIn, Plus, Radio, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import type { SessionUser } from "../components/LoginModal";
import { api } from "../data/api";

interface Alert { id: string; name: string; symbol: string; kind: string; operator: string; targetValue: number; intervalName: string; active: boolean; lastTriggeredAt?: string; }
export function AlertsPage({ user, onLogin, startCreating = false }: { user: SessionUser | null; onLogin: () => void; startCreating?: boolean }) {
  const [alerts, setAlerts] = useState<Alert[]>([]), [creating, setCreating] = useState(startCreating), [symbol, setSymbol] = useState("天娱数科 002354.SZ"), [condition, setCondition] = useState("价格突破"), [value, setValue] = useState("6.68"), [error, setError] = useState(""), [checking, setChecking] = useState(false);
  const load = async () => { if (!user) return; try { setAlerts((await api.alerts()).items); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "加载失败"); } };
  useEffect(() => { load(); }, [user]);
  const addAlert = async (event: FormEvent) => { event.preventDefault(); const [name, code] = symbol.split(" "); const kind = condition.includes("涨跌") ? "change_percent" : condition.includes("成交量") ? "volume" : "price"; const operator = condition.includes("跌破") ? "lte" : "gte"; try { await api.addAlert({ symbol: code, name, kind, operator, targetValue: Number(value), intervalName: "实时" }); setCreating(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "创建失败"); } };
  const toggle = async (alert: Alert) => { try { await api.setAlertActive(alert.id, !alert.active); setAlerts((items) => items.map((item) => item.id === alert.id ? { ...item, active: !item.active } : item)); } catch (e) { setError(e instanceof Error ? e.message : "更新失败"); } };
  const remove = async (id: string) => { try { await api.removeAlert(id); setAlerts((items) => items.filter((item) => item.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : "删除失败"); } };
  const evaluate = async () => { setChecking(true); try { const result = await api.evaluateAlerts(); setError(`检查完成：${result.results.filter((item: any) => item.status === "triggered").length} 条触发`); await load(); } catch (e) { setError(e instanceof Error ? e.message : "检查失败"); } finally { setChecking(false); } };
  if (!user) return <div className="page workspace-page"><div className="workspace-heading"><div><span className="eyebrow">CONDITION MONITOR</span><h1>条件提醒</h1><p>登录后将规则保存至服务端</p></div></div><div className="panel empty-state"><LogIn /><strong>登录后创建提醒</strong><span>提醒规则和触发历史需要账户绑定</span><button className="button button-primary" type="button" onClick={onLogin}>立即登录</button></div></div>;
  return <div className="page workspace-page"><div className="workspace-heading"><div><span className="eyebrow">CONDITION MONITOR · API CONNECTED</span><h1>条件提醒</h1><p>提醒规则由后端持久化并调用真实行情检查</p></div><button className="button button-primary" type="button" onClick={() => setCreating(true)}><Plus />新建提醒</button></div>
    <section className="watch-summary alert-summary"><div><span>监控中</span><strong className="green-text">{alerts.filter((item) => item.active).length}</strong><small>服务端规则</small></div><div><span>最近触发</span><strong className="amber-text">{alerts.filter((item) => item.lastTriggeredAt).length}</strong><small>已落库</small></div><div><span>行情检查</span><button className="button button-secondary" type="button" disabled={checking} onClick={evaluate}>{checking ? "检查中" : "立即执行"}</button><small>手动任务</small></div></section>{error && <p className="api-message">{error}</p>}
    {creating && <form className="panel alert-creator" onSubmit={addAlert}><div className="panel-title">新建条件提醒<button type="button" aria-label="关闭" onClick={() => setCreating(false)}><X /></button></div><div className="alert-form-grid"><label><span>标的</span><select value={symbol} onChange={(e) => setSymbol(e.target.value)}><option>天娱数科 002354.SZ</option><option>贵州茅台 600519.SH</option><option>宁德时代 300750.SZ</option></select></label><label><span>条件</span><select value={condition} onChange={(e) => setCondition(e.target.value)}><option>价格突破</option><option>价格跌破</option><option>涨跌幅达到</option><option>成交量达到</option></select></label><label><span>目标值</span><input value={value} onChange={(e) => setValue(e.target.value)} /></label><button className="button button-primary" type="submit"><Check />创建提醒</button></div></form>}
    <section className="panel alerts-list"><div className="panel-title">全部提醒<span>服务端实时数据</span></div>{alerts.map((alert) => <div className="alert-row" key={alert.id}><span className={`alert-symbol ${alert.active ? "active" : ""}`}>{alert.active ? <Radio /> : <Clock3 />}</span><div><strong>{alert.name}<small>{alert.symbol}</small></strong><p>{alert.kind === "price" ? "价格" : alert.kind === "volume" ? "成交量" : "涨跌幅"} {alert.operator === "gte" ? "≥" : "≤"} {alert.targetValue}</p><span>{alert.intervalName} · {alert.lastTriggeredAt ? `最近触发 ${alert.lastTriggeredAt.slice(5, 16).replace("T", " ")}` : "尚未触发"}</span></div><em className={alert.active ? "running" : "paused"}>{alert.active ? "监控中" : "已暂停"}</em><button className={`switch ${alert.active ? "on" : ""}`} type="button" aria-label={`${alert.active ? "暂停" : "启用"}${alert.name}提醒`} onClick={() => toggle(alert)}><span /></button><button className="delete-alert" type="button" aria-label={`删除${alert.name}提醒`} onClick={() => remove(alert.id)}><Trash2 /></button></div>)}</section><div className="data-disclosure"><BellRing /><span><strong>提醒说明：</strong>规则与触发事件已连接后端；短信和系统推送尚未接入。</span></div></div>;
}
