import { Bell, Bookmark, Check, ChevronRight, CircleUserRound, Cloud, Database, History, KeyRound, LogIn, LogOut, ShieldCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { SessionUser } from "../components/LoginModal";
import { api } from "../data/api";

export function ProfilePage({ user, onLogin, onLogout, onNavigate }: { user: SessionUser | null; onLogin: () => void; onLogout: () => void; onNavigate: (page: "watchlist" | "alerts" | "replay") => void; }) {
  const [stats, setStats] = useState({ reports: 0, watchlist: 0, activeAlerts: 0, uploads: 0 });
  const [passwordOpen, setPasswordOpen] = useState(false), [password, setPassword] = useState(""), [confirmation, setConfirmation] = useState(""), [passwordMessage, setPasswordMessage] = useState("");
  useEffect(() => { if (user) api.profileStats().then(setStats).catch(() => undefined); else setStats({ reports: 0, watchlist: 0, activeAlerts: 0, uploads: 0 }); }, [user]);
  return <div className="page profile-page"><div className="profile-hero"><span className={`profile-avatar ${user ? "online" : ""}`}><CircleUserRound /></span><div>{user ? <><span className="profile-status">账户已同步</span><h1>{user.displayName}</h1><p>{user.phone.slice(0, 3)} **** {user.phone.slice(-4)} · 服务端账户</p></> : <><span className="profile-status guest">游客模式</span><h1>登录析线 AI</h1><p>同步自选、提醒和跨设备分析记录</p></>}</div><button className={`button ${user ? "button-secondary" : "button-primary"}`} type="button" onClick={user ? onLogout : onLogin}>{user ? <LogOut /> : <LogIn />}{user ? "退出登录" : "立即登录"}</button></div>
    <section className="profile-metrics"><div><span>已上传图表</span><strong>{stats.uploads}</strong><small>服务端存储</small></div><div><span>累计报告</span><strong>{stats.reports}</strong><small>数据库记录</small></div><div><span>自选标的</span><strong>{stats.watchlist}</strong><small>云端同步</small></div><div><span>运行提醒</span><strong>{stats.activeAlerts}</strong><small>条件监控</small></div></section>
    <div className="profile-grid"><section className="panel profile-menu"><div className="panel-title">研究工作区</div><button type="button" onClick={() => onNavigate("watchlist")}><Bookmark /><span><strong>我的自选</strong><small>行情、AI 结构与分组管理</small></span><ChevronRight /></button><button type="button" onClick={() => onNavigate("alerts")}><Bell /><span><strong>条件提醒</strong><small>价格、量能与事件监控</small></span><ChevronRight /></button><button type="button" onClick={() => onNavigate("replay")}><History /><span><strong>分析复盘</strong><small>验证历史判断与条件触发</small></span><ChevronRight /></button></section><section className="panel profile-menu"><div className="panel-title">账户与数据</div><button type="button"><Cloud /><span><strong>同步状态</strong><small>{user ? "服务端同步正常" : "登录后开启同步"}</small></span><em className={user ? "ok" : ""}>{user ? "已连接" : "未登录"}</em></button><button type="button"><Database /><span><strong>数据网关</strong><small>行情、财务与公告源</small></span><em className="ok">API 正常</em></button>{user && <button type="button" onClick={() => setPasswordOpen(true)}><KeyRound /><span><strong>{user.hasPassword ? "修改登录密码" : "设置登录密码"}</strong><small>{user.hasPassword ? "更新账户密码" : "设置后可使用密码登录"}</small></span><ChevronRight /></button>}<button type="button"><ShieldCheck /><span><strong>隐私与安全</strong><small>令牌会话与上传文件隔离</small></span><ChevronRight /></button></section></div><p className="workspace-disclosure">账户、自选、提醒、上传与报告统计已连接本地后端服务。</p>
    {passwordOpen && <div className="auth-overlay"><form className="auth-modal password-modal" onSubmit={async (event) => { event.preventDefault(); if (password.length < 8) return setPasswordMessage("密码至少需要 8 位"); if (password !== confirmation) return setPasswordMessage("两次输入的密码不一致"); try { await api.setPassword(password); if (user) user.hasPassword = true; setPasswordMessage("密码设置成功"); window.setTimeout(() => setPasswordOpen(false), 650); } catch (error) { setPasswordMessage(error instanceof Error ? error.message : "设置失败"); } }}><button className="auth-close" type="button" aria-label="关闭" onClick={() => setPasswordOpen(false)}><X /></button><div className="auth-heading"><span>ACCOUNT SECURITY</span><h2>{user?.hasPassword ? "修改登录密码" : "设置登录密码"}</h2><p>密码将由服务端使用 scrypt 加盐哈希保存</p></div><div className="auth-form"><label><span>新密码</span><div className="auth-field"><KeyRound /><input type="password" placeholder="至少 8 位" value={password} onChange={(event) => setPassword(event.target.value)} /></div></label><label><span>确认密码</span><div className="auth-field"><Check /><input type="password" placeholder="再次输入密码" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></div></label>{passwordMessage && <p className="api-message">{passwordMessage}</p>}<button className="auth-submit" type="submit"><ShieldCheck />保存密码</button></div></form></div>}
  </div>;
}
