import { ArrowDownRight, ArrowUpRight, BellPlus, LogIn, Plus, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { SessionUser } from "../components/LoginModal";
import { api } from "../data/api";

interface Stock { id: string; symbol: string; name: string; groupName: string; price: number; change: number; updated: string; }
export function WatchlistPage({ user, onLogin, onCreateAlert }: { user: SessionUser | null; onLogin: () => void; onCreateAlert: () => void }) {
  const [stocks, setStocks] = useState<Stock[]>([]), [query, setQuery] = useState(""), [group, setGroup] = useState("全部"), [error, setError] = useState("");
  const [adding, setAdding] = useState(false), [symbol, setSymbol] = useState("002354.SZ"), [name, setName] = useState("天娱数科");
  const load = async () => { if (!user) return setStocks([]); try { const result = await api.watchlist(); const enriched = await Promise.all(result.items.map(async (item) => { try { const data = await api.research(item.symbol); return { ...item, price: data.quote?.price ?? 0, change: data.quote?.changePercent ?? 0, updated: data.quote?.retrievedAt?.slice(11, 16) ?? "--" }; } catch { return { ...item, price: 0, change: 0, updated: "--" }; } })); setStocks(enriched); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "加载失败"); } };
  useEffect(() => { load(); }, [user]);
  const add = async () => { if (!user) return onLogin(); try { await api.addWatch({ symbol, name, groupName: "重点观察" }); setAdding(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "添加失败"); } };
  const remove = async (id: string) => { try { await api.removeWatch(id); setStocks((items) => items.filter((item) => item.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : "移除失败"); } };
  const filtered = useMemo(() => stocks.filter((stock) => (group === "全部" || stock.groupName === group) && `${stock.name}${stock.symbol}`.toLowerCase().includes(query.toLowerCase())), [group, query, stocks]);
  if (!user) return <div className="page workspace-page"><div className="workspace-heading"><div><span className="eyebrow">WATCHLIST</span><h1>我的自选</h1><p>登录后同步自选行情与提醒</p></div></div><div className="panel empty-state"><LogIn /><strong>登录后使用自选股</strong><span>数据将保存到服务端并支持跨设备同步</span><button className="button button-primary" type="button" onClick={onLogin}>立即登录</button></div></div>;
  return <div className="page workspace-page"><div className="workspace-heading"><div><span className="eyebrow">WATCHLIST · API CONNECTED</span><h1>我的自选</h1><p>行情来自公开数据网关，自选记录保存于服务端</p></div><button className="button button-primary" type="button" onClick={() => setAdding(!adding)}><Plus />添加标的</button></div>
    {adding && <section className="panel inline-add"><input value={symbol} onChange={(e) => setSymbol(e.target.value.toUpperCase())} placeholder="股票代码" /><input value={name} onChange={(e) => setName(e.target.value)} placeholder="股票名称" /><button className="button button-primary" type="button" onClick={add}>保存到自选</button></section>}{error && <p className="api-error">{error}</p>}
    <section className="watch-summary"><div><span>自选标的</span><strong>{stocks.length}</strong><small>服务端记录</small></div><div><span>今日上涨</span><strong className="green-text">{stocks.filter((item) => item.change > 0).length}</strong><small>实时查询</small></div><div><span>数据状态</span><strong className="green-text">已连接</strong><small>API 8787</small></div></section>
    <section className="panel watch-panel"><div className="watch-toolbar"><div className="watch-groups">{["全部", "重点观察", "核心资产"].map((item) => <button type="button" className={group === item ? "active" : ""} onClick={() => setGroup(item)} key={item}>{item}</button>)}</div><label className="watch-search"><Search /><input placeholder="搜索名称或代码" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div><div className="watch-table"><div className="watch-row watch-header"><span>标的</span><span>最新价</span><span>涨跌幅</span><span>行情状态</span><span>分组</span><span>操作</span></div>{filtered.map((stock) => <div className="watch-row" key={stock.id}><span><strong>{stock.name}</strong><small>{stock.symbol} · {stock.updated}</small></span><span className="watch-price">{stock.price ? stock.price.toFixed(2) : "--"}</span><span className={stock.change >= 0 ? "green-text" : "red-text"}>{stock.change >= 0 ? <ArrowUpRight /> : <ArrowDownRight />}{stock.change > 0 ? "+" : ""}{stock.change.toFixed(2)}%</span><span><em className="signal-pill positive">已核验</em></span><span className="muted-cell">{stock.groupName}</span><span className="row-actions"><button type="button" aria-label={`为${stock.name}创建提醒`} onClick={onCreateAlert}><BellPlus /></button><button type="button" aria-label={`移除${stock.name}`} onClick={() => remove(stock.id)}><Trash2 /></button></span></div>)}</div>{filtered.length === 0 && <div className="empty-state"><Search /><strong>暂无自选标的</strong><span>点击右上角添加并保存到服务端</span></div>}</section><p className="workspace-disclosure">行情使用低成本公开接口，仅用于 MVP 验证，不构成投资建议。</p></div>;
}
